<?php

namespace Api\Newsreader;

class GNewsTopHeadlinesEndpoint extends GNewsEndpoint
{
    public $topic;
    const TOPHEADLINES = "top-headlines?";

    public function __construct($topic,$searchText, $lang, $country, $fromDate, $toDate)
    {
        parent::__construct($searchText, $lang, $country, $fromDate, $toDate);
        $this->topic = $topic;
    }

    public function GetFilterString()
    {
        $filter = parent::GetFilterString(); // TODO: Change the autogenerated stub)
        if (!empty($topic)){
            $filter = 'topic='.$this->topic;
            if(!empty($abc)){
                $filter = 'topic='. $this->topic. '&'.$filter;
            }
        }
        return self::TOPHEADLINES.$filter;
    }
}